### PR TITLE
Nuget download location

### PR DESCRIPTION
**Pull request by frozenskys**
Adds advanced settings to fix Issue #4 by allowing nuget to be downloaded from an alternate file\web location and\or use an alternate feed for initial cake\tool installation.

screenshot_2

Not sure about your naming conventions, etc. so have made a best guess.

### CODE REVIEW

**Comment by rj-cooper** [comment]
Need to update documentation as mentioned in Issue #31

**Comment by rj-cooper** [comment]
@gep13 @devlead Any idea how we can test this? I've only got an on prem TFS vNext install that I can test with, and I haven't seen any example xunit style tests for build tasks. How did you test the original release?

**Comment by gep13** [comment]
@frozenskys we have an internal documented process on how to test out the VSTS extension.  I would just need to find some cycles in order to test it out.  I will try to make some time for this.

**Comment by rj-cooper** [comment]
@gep13 Cool - I'll try and smoke test it on my VM tonight, as that will give me an early view of anything that's broken - but I find TFS '15' is way more tolerant of broken extensions than TFS 2015.3

**Comment by rj-cooper** [comment]
Added some fixes for the using the build agent nuget.exe - in order to use this when actually running the cake script rather than from the task, we need to copy nuget.exe into the cake tool folder.

**Comment by rfvgyhn** [comment]
Any word on getting this merged?

**Comment by fleed** [comment]
when will this change be published? I'm currently having problems running build on VSTS because of the nuget version.

**Comment by StevenWolfe** [comment]
@frozenskys is there anything I can lend a hand with?  We just migrated to VSO and can't run Cake due to the requirement for NuGet 3.0+, so we're falling back to running the build.ps1 via a Powershell Task--but would really like to plug directly into Cake ASAP.

Thanks!

**Comment by jnm2** [comment]
My company needs NuGet v4.0.

**Review by agc93 — APPROVED** [review]
LGTM 👍

**Comment by agc93** [comment]
Thanks very much @frozenskys for this awesome contribution! Your changes have now been merged and will be included in the next release of the VSTS extension.

**Comment by mmisztal1980** [comment]
Is this changeset released to VSTS yet?

**Comment by gep13** [comment]
>@mmisztal1980 said...
Is this changeset released to VSTS yet?

No, this hasn't been deployed yet.  I believe we are on the cusp of doing it though. @agc93 can you confirm?

**Comment by mmisztal1980** [comment]
@gep13 cheers Gary.

**Comment by saberone** [comment]
Any news on this being deployed to vsts? And if not is there a workaround to make the Xunit tests run in VSTS and report the results?

**Comment by devlead** [comment]
@agc93 working on getting it out as soon as possible, it's mostly done, but there's a little ceremony left and little spare time to do it 😉

**Comment by VictorioBerra** [comment]
@frozenskys Since this is now out, can you please update your review? https://marketplace.visualstudio.com/items?itemName=cake-build.cake&ssr=false#overview

**Pull request merged**
