### PR TITLE
(GH-48) Update task handler

### PR DESCRIPTION
**Pull request by richardgavel**

### CODE REVIEW

**Comment by richardgavel** [comment]
Fixes https://github.com/cake-build/cake-vso/issues/48

**Comment by dv42** [comment]
Is any help needed in order to merge this PR?

**Comment by gep13** [comment]
@richardgavel @dv42 as mentioned here: https://github.com/cake-build/cake/issues/2723#issuecomment-591194599 I am going to try to take a look at this tomorrow evening.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@richardgavel your changes have been rebased and merged here: 

https://github.com/cake-build/cake-vso/commit/95b9f11b6973dd243b48cb3aae7414cdf03f6512

Thanks for your contribution 👍

Since the GitHub UI doesn't follow the action that I have taken, I am going to go ahead and close this PR, but your work has still been correctly attributed in the develop branch.  I appreciate you taking the time to do this work, and for following up on it.

**Comment by gep13** [comment]
@richardgavel @dv42 I have just published 0.4.0 of this extension.  Can you take it for a spin and let me know if this has fixed the issue that you were seeing?  Thanks

**Comment by dv42** [comment]
@gep13 we didn't pin cake task in Azure DevOps so all pipelines were migrated to 0.4.0 automatically and all cake-related warnings disappeared. Everything looks good on my end.

**Comment by gep13** [comment]
@dv42 thanks for getting back to me.  There were a couple of issues reported with the latest release, so you should find that there will be a 0.4.2 version available in the next couple minutes, but if you haven't been affected, you have nothing to worry about.

**Comment by richardgavel** [comment]
@gep13 0.42 is giving me errors

```
##[debug]Evaluating condition for step: 'Compile & Unit tests'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Compile & Unit tests
==============================================================================
Task         : Cake
Description  : Build with Cake
Version      : 0.4.2
Author       : Patrik Svensson
Help         : [More Information about Cake](https://cakebuild.net)
==============================================================================
##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
##[debug]INPUT_SCRIPT: 'C:\vsts-agent-3\_work\2\s\build.cake'
##[debug]INPUT_TARGET: 'Default'
##[debug]INPUT_VERBOSITY: 'Diagnostic'
##[debug]INPUT_ARGUMENTS (empty)
##[debug]INPUT_USEBUILDAGENTNUGETEXE: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_NUGETEXEDOWNLOADLOCATION (empty)
##[debug]INPUT_TOOLFEEDURL (empty)
##[debug]==============================================
##[debug]Root = C:\vsts-agent-3\_work\2\s
##[debug]Tools = C:\vsts-agent-3\_work\2\s\tools
##[debug]Packages = C:\vsts-agent-3\_work\2\s\tools\packages.config
##[debug]Modules = C:\vsts-agent-3\_work\2\s\tools\Modules
##[debug]Cake = C:\vsts-agent-3\_work\2\s\tools\Cake\Cake.exe
##[debug]NuGet = C:\vsts-agent-3\_work\2\s\tools\nuget.exe
##[debug]==============================================
##[debug]Getting nuget.exe from 
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]ForEach-Object : Exception calling "DownloadFile" with "2" argument(s): "The path is not of a legal form."
##[debug]At line:19 char:13
##[debug]+             ForEach-Object {
##[debug]+             ~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
##[debug]    + FullyQualifiedErrorId : ArgumentException,Microsoft.PowerShell.Commands.ForEachObjectCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, C:\vsts-agent-3\_work\_tasks\Cake_b88ea9a0-7d6e-11e5-b5de-d57d652482f7\0.4.2\Cake.ps1: line 58
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.MethodInvocationException: Exception calling "DownloadFile" with "2" argument(s): "The path is not of a legal form." ---> System.ArgumentException: The path is not of a legal form.
##[debug]   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
##[debug]   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
##[debug]   at System.IO.Path.GetFullPathInternal(String path)
##[debug]   at System.Net.WebClient.GetUri(String path)
##[debug]   at System.Net.WebClient.DownloadFile(String address, String fileName)
```

**Comment by gep13** [comment]
@richardgavel Hmm, that is very strange!

On the same build, would you mind adding a PowerShell Task, and then adding the following to it:

```
$nugetExeDownloadLocation = (Get-Command nuget -ErrorAction SilentlyContinue).Source;
Write-Host $nugetExeDownloadLocation
$nugetExeDownloadLocation -eq ""
$nugetExeDownloadLocation -eq $null

Get-Command nuget
```

And then run the build, and let me know what comes back?

**Comment by dv42** [comment]
@gep13  I have same issue. Output for the PowerShell script is next:

```
2020-02-28T05:05:48.0311919Z C:\hostedtoolcache\windows\NuGet\4.8.2\x64\nuget.exe
2020-02-28T05:05:48.0350065Z False
2020-02-28T05:05:48.0353915Z False
2020-02-28T05:05:50.3716176Z 
2020-02-28T05:05:50.3736800Z CommandType     Name                                               Version    Source                                   
2020-02-28T05:05:50.3750459Z -----------     ----                                               -------    ------                                   
2020-02-28T05:05:50.3790601Z Application     nuget.exe                                          4.8.2.0    C:\hostedtoolcache\windows\NuGet\4.8.2...
2020-02-28T05:05:50.4249414Z 
```

**Comment by dv42** [comment]
@gep13 @richardgavel I found a workaround.
My build passed once I explicitly set `Use the Build Agent Nuget`  to true (in yaml it is `useBuildAgentNuGetExe: true`)

so it's the opposite bug to https://github.com/cake-build/cake-vso/issues/56

**Pull request closed without merging**
